extends Node

enum GRID_OBJECT_TYPE {GRID_NONE=-1, GRID_ROCK, GRID_COAL, GRID_COPPER, GRID_IRON, GRID_RADICAL, GRID_MULTI_CELL, GRID_MULTI_CELL_SUBCELL}

const TILES_PER_SIDE = 25

const CELL_SIZE_PIXELS = 17.0
